services:
  - type: web
    name: mhtcet-college-finder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -w 4 -k uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
